# Operaciones Matemáticas y Estadística

In [2]:
import numpy as np

## Operaciones entre arrays y escalares

- Las operaciones entre arrays y escalares se hacen término a término

In [3]:
array = np.array([[1, 2, 3], [4, 5, 6]])
array

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
array * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [5]:
array - 1

array([[0, 1, 2],
       [3, 4, 5]])

In [6]:
1 / array 

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [7]:
array**2

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

## Operaciones matemáticas con arrays

- Vamos a probar distintos tipos de funciones, así como operaciones entre arrays
- Las operaciones entre arrays deben de cumplir las condiciones de broadcasting
- Se pueden ver todas las funciones disponibles [aquí](https://numpy.org/doc/stable/reference/routines.math.html)
- Las más usadas son:

|Función|Descripcción|
|----|---|
|`abs, fabs`| Valor absoluto.|
|`sqrt`| Raíz cuadrada (equivalente a array \*\* 0.5).|
|`square`| Potencia al cuadrado (equivalente a array ** 2).|
|`exp`| Potencia de e.|
|`log, log10, log2, log1p`| Logaritmos en distintas bases.|
|`ceil`| Techo.|
|`floor`| Suelo.|
|`rint`| Redondeo al entero más cercano.|
|`modf`| Devuelve dos arrays uno con la parte fraccionaria y otro con la parte entera.|
|`isnan`| Devuelve un array booleano indicando si el valor es NaN o no.|
|`isfinite, isinf`| Devuelve un array booleano indicando si el valor es finito o no.|
|`cos, cosh, sin, sinh, tan, tanh`| Funciones trigonométricas.|
|`arccos, arccosh, arcsin, arcsinh, arctan, arctanh`| Funciones trigonométricas inversas.|
|`logical_not`| Inverso booleano de todos los valores del array (equivalente a -(array)).|

In [15]:
array_1 = np.arange(6)
array_2 = np.arange(6,12)
print(array_1)
print(array_2)

[0 1 2 3 4 5]
[ 6  7  8  9 10 11]


In [16]:
array_1 + array_2

array([ 6,  8, 10, 12, 14, 16])

In [17]:
array_1 * array_2

array([ 0,  7, 16, 27, 40, 55])

In [18]:
array_1 ** array_2

array([       0,        1,      256,    19683,  1048576, 48828125],
      dtype=int32)

- Ahora vamos a ver distintas funciones, que son muy utilizadas

In [20]:
array_1 = np.arange(6)**2
array_1

array([ 0,  1,  4,  9, 16, 25], dtype=int32)

In [21]:
np.sqrt(array_1)

array([0., 1., 2., 3., 4., 5.])

In [29]:
array_2 = np.linspace(0, 2*np.pi, 5)
array_2

array([0.        , 1.57079633, 3.14159265, 4.71238898, 6.28318531])

In [30]:
np.sin(array_2)

array([ 0.0000000e+00,  1.0000000e+00,  1.2246468e-16, -1.0000000e+00,
       -2.4492936e-16])

## Funciones incorporadas en arrays

- Los arrays llevan incorporadas funciones (métodos) tanto matemáticas como estadísticas.
- Todos los métodos de los arrays se pueden consultar [aquí](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html)

|Función|Descripcción|
|----|---|
|`sum`| Suma de elementos.|
|`mean`| Media aritmética de los elementos.|
|`median`| Mediana de los elementos.|
|`std`| Desviación estándar de los elementos.|
|`var`| Varianza de los elementos.|
|`min`| Valor mínimo de los elementos.|
|`max`| Valor máximo de los elementos.|
|`argmin`| Índice del valor mínimo.|
|`argmax`| Índice del valor máximo.|
|`cumsum`| Suma acumulada de los elementos.|
|`cumprod`| Producto acumulado de los elementos.|


In [32]:
array_1 = np.arange(6)
array_1

array([0, 1, 2, 3, 4, 5])

In [34]:
array_1.sum()

15

In [35]:
array_1.min()

0

In [36]:
array_1.max()

5

In [37]:
array_1.mean()

2.5

___
## Ejercicios

**1** Crea un array con los numeros del 0 al 100:
    - crea una variable con los anteriores valores en forma de matriz 10x10
    - multiplica el primer vector término a término por 5
    - saca la media y la desviación estándar del primer vector

**2** Genera un array aleatorio de 100 posiciones y muestra los cuantiles 95 y 5

**3**  Crea una función que sume el valor absoluto de todos los elementos negativos de una matriz recibida como parámetro. O devuelva "No hay negativos" en caso de que no los haya.